name: "Update packages"

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"

jobs:
  update:
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Run updater
      run: |
        export NEXTCLOUD_VERSIONS=$(nix-instantiate --eval -E "import ./nc-versions.nix { env = true; }")
        nix run nixpkgs#go_1_24 run main.go

    - name: Commit and push
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

